### PR TITLE
Add final payment request for pktchat_upgrade project Milestone #2 through #9

### PR DESCRIPTION
**Pull request by thierrymarianne**
Here is current [pkt.chat](https://pkt.chat) upgrade status:

 - a [pull-request covering Milestone #​1](https://github.com/cjdelisle/Matterfoss/pull/9), 
 which also contains some timesheet (~ 16 hours i.e. 2 business days were consumed) was opened,  
   before being superseded by [matterfoss-v6.6.1 release](https://github.com/cjdelisle/Matterfoss/releases/tag/matterfoss-v6.6.1)
 - a [pull-request covering Milestone #​​2 through #​5](https://github.com/cjdelisle/MatterfossWeb/pull/12) was opened,  
  before being superseded by [matterfoss-webapp-v6.6.1 release](https://github.com/thierrymarianne/contrib-matterfoss-webapp/releases/tag/matterfoss-webapp-v6.6.1)
 - Milestones #​6, #​7, and #​9 were coordinated with @cjdelisle last week (19th)
 - Milestone #​8 has been taken care of with [this post](https://pkt.chat/pkt/pl/b4a6ou5sc3nejd6376mmgm4n1h) 
 - Final payment request for Milestone #​2 through #​9 is hereby submitted
 
Milestones #​2 through #​9 were covered in 77 hours (roughly 10 business days).
You'll find another timesheet attached to this pull-request (going from the 5th of May to the 16th of May)

I believe that the initial goal has been reached:
 - Native mobile app (tested for Android) doesn't show a dialog box anymore 
   about server upgrade being needed.
   A demo has been uploaded and is available from [https://youtube.com/shorts/kQsEoQg3lr0?feature=share - 11s](https://youtube.com/shorts/kQsEoQg3lr0?feature=share) and
 - The welcome workflow based on previous work involving bots appears to be intact
   A demo has been uploaded and is available from [https://youtu.be/3Q896K1lrvY - 31s](https://youtu.be/3Q896K1lrvY)

I hope everything is clear. Please let me know if it is not.

[pktchat upgrade project timesheet (2022-05-05-2022-05-16)](https://github.com/pkt-cash/ns-projects/files/8701453/2022-05-05_to_2022-05-16_pkt_chat_upgrade.CSV)

### CODE REVIEW

**Review by cjdelisle — APPROVED** [review]
I think this PR should be accepted because pkt.chat has been updated and works well.
However payment should be limited to 223973 PKT for a sum total of 275000 PKT as per original project request.

**Review by Arceliar — APPROVED** [review]
Ideally, I would prefer not to see multiple milestones being submitted for approval at once, but I suppose these seem small enough that it's not too much of an issue to bundle them together.

I don't use pkt.chat myself, but assuming that there are no specific objections raised by users or other NS members, then I defer to @cjdelisle's assessment that the goals have been met and agree re. acceptance and payout.

**Review by dvn0 — APPROVED** [review]
Looks good to me regarding content of the request. I'm also deferring to @cjdelisle on the assessment of the final quality of the work, but a cursory overview of the associated PRs shows me that things were handled appropriately.

**Comment by cjdelisle** [comment]
Regarding payment, I'm making the txn now. If you want to be paid more than the max amount of PKT then you can make an application for that but it will then need to be reviewed by the whole team.

**Pull request merged**
