### PR TITLE
Update 2020_02_28_Proposal_Cjdns_using_Wireguard_for_encryption.md

### PR DESCRIPTION
**Pull request by Ilgiz22**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Dear Alex,

I would like to get this project paid very soon, but purely for cross-T's-dot-i's purposes, I would 
like an email confirmation of the request to change payout address.

We will be changing the payout address from:

* PKT address: pKHsMf6Eg8YB2jTJUpdRbCj7RpvpMpYRkU

To:

* PKT address: pkt1qux6nhrz37pcfx60ppzsaf3c3zc05a4r4yqqtwk

A simple reply to this email will be sufficient.

Thanks,
Caleb

**Comment by cjdelisle** [comment]
Yea that is correct. Thank you for payment, Caleb. I hope you are well.

**Review by cjdelisle — APPROVED** [review]

**Comment by cjdelisle** [comment]
This appears as a comment from me but I received the email correctly so I am approving this now

**Review by backupbrain — APPROVED** [review]

**Comment by benhylau** [comment]
Can @EliasMesh confirm since that's the account that made the original proposal?

**Comment by cjdelisle** [comment]
Hello Alex,

Thanks for your confirmation. Finally it seems I moved a bit fast and in fact my colleagues in the 
NS would prefer to see the original creator of the proposal make the request on github. Do you think 
you can get the account EliasMesh, aka https://github.com/EliasMesh to write a comment on this PR:
https://github.com/pkt-cash/ns-projects/pull/62
to confirm that the change of address is intended.

I'm sorry for the surprise complexity here but I respect the intent of my colleagues to make doubly 
sure that we are taking the correct action.

Thanks,
Caleb

**Comment by benhylau** [comment]
@cjdelisle forwarded a copy of the confirmation email from Alex and I will keep on record

**Review by benhylau — APPROVED** [review]

**Comment by EliasMesh** [comment]
I approve change of the address.  
* PKT address: pKHsMf6Eg8YB2jTJUpdRbCj7RpvpMpYRkU 
To:
* PKT address: pkt1qux6nhrz37pcfx60ppzsaf3c3zc05a4r4yqqtwk

**Review by Arceliar — APPROVED** [review]

**Review by neilalexander — APPROVED** [review]

**Pull request merged**
