### PR TITLE
Update 2019_12_14_pkt-whitepaper-website.md

### PR DESCRIPTION
**Pull request by josh-berger**
I am asking that this submission be granted as Milestone 1 & 3 combined. This is because an initial whitepaper was submitted and rejected. So technically a review process has already occurred. If there are any comments that need to be addressed to make this whitepaper correct, please let me know. If you think this whitepaper is acceptable, I would like for this to be accepted as Milestone 1& 3.

### CODE REVIEW

**Comment by cjdelisle** [comment]
I'm going to sit this one out because my name is on the WP here so I have an obvious conflict, but I'd like to get a review from the team.

**Comment by Arceliar** [comment]
I had a chance to read the whitepaper. Overall I think it's OK as-is, but I have a few comments / suggestions.

# General comments:

Would it make sense to add a section on related work? I usually see this somewhere near the beginning of papers. There are a few other projects that attempt to tackle largely the same problem through similar means (Althea and Skycoin come to mind), so I think it could make sense to acknowledge that they exist and spend a few words summarizing what cjdns+PKT does differently (basically, answer the question "Why should I care about PKT if $PROJECT already exists?" for projects the target audience is most likely to be familiar with).

## Section 2.1

It may make sense to walk through a multi-hop example, to show how priority set in an uncongested region of the network leads to the intended transmission rates in the congested region. Or perhaps, if that's out-of-scope for the whitepaper, to have such a description somewhere else and cite it in this section. Otherwise this feels a bit like "proof is left as an exercise to the reader" (which I don't think is ideal).

## Section 6.2

The text says *that* PacketCrypt incentivizes bandwidth, but it doesn't really explain *how* it does this (it references the PacketCrypt paper, but doesn't really go into any more detail). I think it would be nice to give a high-level overview / summary of how increased bandwidth leads to an increased number of (higher quality) announcements, which leads to a higher effective mining rate, and then cite the PacketCrypt paper for anyone who wants the full technical description. Considering how often the bandwidth-incentivizing / bandwidth-hard nature of PacketCrypt is mentioned, and how important that is the the project overall, I could see the reader being left confused or feeling like they've just been told to "RTFM" by one of the most important sections of the whitepaper.

# Editorial comments:
## Section 1
>  "... the press that[,] in a time of political upheaval, could prove catastrophic."

## Section 4

It looks a little weird for (*SDN*) and (*VPN*) to be in italics. Maybe italicize the full terms when they're first being defined, and leave the abbreviations umemphasized?

## Section 8.3
>"... can be traced from one party to the next[.] [H]owever[,] similar to Ethereum ..."

**Review by Arceliar — COMMENTED** [review]
I had a chance to read the whitepaper. Overall I think it's OK as-is, but I have a few comments / suggestions.

# General comments:

Would it make sense to add a section on related work? I usually see this somewhere near the beginning of papers. There are a few other projects that attempt to tackle largely the same problem through similar means (Althea and Skycoin come to mind), so I think it could make sense to acknowledge that they exist and spend a few words summarizing what cjdns+PKT does differently (basically, answer the question "Why should I care about PKT if $PROJECT already exists?" for projects the target audience is most likely to be familiar with).

## Section 2.1

It may make sense to walk through a multi-hop example, to show how priority set in an uncongested region of the network leads to the intended transmission rates in the congested region. Or perhaps, if that's out-of-scope for the whitepaper, to have such a description somewhere else and cite it in this section. Otherwise this feels a bit like "proof is left as an exercise to the reader" (which I don't think is ideal).

## Section 6.2

The text says *that* PacketCrypt incentivizes bandwidth, but it doesn't really explain *how* it does this (it references the PacketCrypt paper, but doesn't really go into any more detail). I think it would be nice to give a high-level overview / summary of how increased bandwidth leads to an increased number of (higher quality) announcements, which leads to a higher effective mining rate, and then cite the PacketCrypt paper for anyone who wants the full technical description. Considering how often the bandwidth-incentivizing / bandwidth-hard nature of PacketCrypt is mentioned, and how important that is the the project overall, I could see the reader being left confused or feeling like they've just been told to "RTFM" by one of the most important sections of the whitepaper.

# Editorial comments:
## Section 1
>  "... the press that[,] in a time of political upheaval, could prove catastrophic."

## Section 4

It looks a little weird for (*SDN*) and (*VPN*) to be in italics. Maybe italicize the full terms when they're first being defined, and leave the abbreviations umemphasized?

## Section 8.3
>"... can be traced from one party to the next[.] [H]owever[,] similar to Ethereum ..."

**Comment by Arceliar** [comment]
Sorry, did not mean to close when I submitted my review.

**Review by Arceliar — APPROVED** [review]
Thinking a bit more, I'll go ahead and approve it as-is. My comments from the earlier review still stand, but I don't want to slow this approval down with discussion over them. I wouldn't mind seeing the editorial comments addressed (minor typos, etc), but content-wise the remaining comments can be thought of more as suggestions for a later draft (if/when that happens).

**Comment by benhylau** [comment]
LGTM both paper and deck.

**Review by benhylau — APPROVED** [review]

**Comment by cjdelisle** [comment]
@backupbrain you merged the PR rather than giving your opinion

**Comment by neilalexander** [comment]
Overall I am happy with the deliverables here, although since the PR has been seemingly already merged, I’m unable to submit a GH review stating such.

**Pull request merged**
