### PR TITLE
Update 2020_11_14-pkt-community.md

### PR DESCRIPTION
**Pull request by josh-berger**

### CODE REVIEW

**Review by cjdelisle — CHANGES_REQUESTED** [review]
* Videos: All complete, only 4 are listed but the 5th one was in the first milestone
* Anim video: Complete
* Article: 4 of 6 complete and present. Other 2 were submitted in M1.
* Tech Article: 4 of 6 complete and present. Other 2 submitted in M1.
* Graphics: Completed, but please make them also available via a place like here: https://pkt.cash/brand/ so that it is clear that they can be downloaded, shared and remixed in accordance with the Creative Commons license, including by people who do not have Instagram accounts.
* WWW_DOCS: Complete
* WWW_I18N: Complete, of note Korean was replaced with Japanese and Russian, but this is in my judgement an acceptable change.
* WWW_UPDATE: Complete

---
I make note that: 
1. The article `cryptopolitan.com/decentralize-everything-a-reminder-for-a-true-community-power` has a paragraph describing PKT but is not an article *about* PKT.
2. The Tech Articles, as "Technical explanations of PKT, PacketCrypt and other aspects of the project" provided fall a bit short of my ideal.

These critiques noted, I also note that certain work has taken place which was not specified here:
* [Many updates to pkt.cash](https://github.com/pkt-cash/www-pkt-cash/pulls?q=is%3Apr+is%3Aclosed+author%3Acoconut3-dev) by the same github user who submitted the translations
* [PKT twitter](https://twitter.com/pkt_cash) using many of the assets from the GRAPHICS deliverable
* [PKT reddit)(https://www.reddit.com/r/PKTcash/) moderated by people who submitted this project.
* A multitude of news articles (google: news: pkt cash) many of which may be organic, but would likely not have existed without this project.

I lay out my analysis such that other members of the NS team may easily decide whether they agree or disagree, but based on the deliverables and the facts of the matter, I think it is quite safe to say that the applicant has used the funds carefully for the purpose described and therefore this deliverable is validated.

I approve this pending upload of the graphical assets to a location more permanent and accessible than instagram.

**Review by josh-berger — COMMENTED** [review]
I have updated the depository of assets.

**Review by cjdelisle — APPROVED** [review]
I can confirm based on the updated PR that there are 28 graphics in the google drive.

**Comment by josh-berger** [comment]
I became aware that at least three of these articles were not written by the community team. I am withdrawing this milestone and will be resubmitting. I’m incredibly sorry.

**Pull request closed without merging**
