### PR TITLE
PKT Lobby Marketing Plan

### PR DESCRIPTION
**Pull request by MeshMode**

### CODE REVIEW

**Comment by cjdelisle** [comment]
NOTE: This proposal seems to specify `320+80+160+160` hours of total effort input between the participants and is asking for a contribution of 8mn PKT, which at the informal trading chat price of 0.05, would put the average hourly cost at $555/hr.
NOTE 2: This proposal makes certain provision to reduce scope in case PKT price falls but in case of price rise, still asks for the entire payout.

**Comment by bonnbonn88** [comment]
The expenses for this project are not limited to hourly rate of 4 people of the core team.

Expenses include renting equipment, hiring people, paying platforms to
promote lobbying materials, paying for access to advisors, travel expenses, research expenses before project is launched to the public,
cost of creation of promotional materials, and more.

Expenses include Dossier and research documents 10k

Rental of recording equipment 10k

Cost of video editing 10k

Paying Influencers 25k-50k x 5 or more depending on how many
Politicians and Influencers want to help with this project.

Cost of promotion of videos and lobbying materials on social media
platforms 10k-50k per month.

Cost of promoting podcasts, videos and legislature material on
multiple networks 10k-50k per month

Cost of creating original Legislature and Bills following all
protocols to be submitted to US government 25k

Cost of travel to meet Politicians and Legislators 10k

Cost of researching all the politicians to reach and inform in regards
to Internet freedom with VPN mesh network marketplaces 10k

Cost of hiring additional lobbying teams to extend outreach on Social
Media 20k-40k per month


Cost of hiring people to call up politicians to promote Internet Freedom and to manage them
10k for 2 months = 20K

Initial cost of testing materials on social media so that they are well received by the public 10-15K


All of these expenses will be covered by the sale of PKT at market price.

The current market price of PKT according the PKT Cash Trading Group
is between .03-.04 cents.

**Comment by bonnbonn88** [comment]
The expenses for this project are not limited to hourly rate of 4
people of the core team.

Expenses include renting equipment, hiring people, paying platforms to
promote lobbying materials, paying for access to advisors, travel
expenses, research expenses before project is launched to the public,
cost of creation of promotional materials, and more.

Expenses include Dossier and research documents 10k

Rental of recording equipment 10k

Cost of video editing 10k

Paying Influencers 25k-50k x 5 or more depending on how many
Politicians and Influencers want to help with this project.

Cost of promotion of videos and lobbying materials on social media
platforms 10k-50k per month.

Cost of promoting podcasts, videos and legislature material on
multiple networks 10k-50k per month

Cost of creating original Legislature and Bills following all
protocols to be submitted to US government 25k

Cost of travel to meet Politicians and Legislators 10k

Cost of researching all the politicians to reach and inform in regards
to Internet freedom with VPN mesh network marketplaces 10k

Cost of hiring additional lobbying teams to extend outreach on Social
Media 20k-40k per month


Cost of hiring people to call up politicians to promote Internet
Freedom and to manage them
10k for 2 months = 20K

Initial cost of testing materials on social media so that they are
well received by the public 10-15K





All of these expenses will be covered by the sale of PKT at market price.

The current market price of PKT according the PKT Cash Trading Group
is between .03-.04 cents.

**Comment by bonnbonn88** [comment]
> NOTE: This proposal seems to specify `320+80+160+160` hours of total effort input between the participants and is asking for a contribution of 8mn PKT, which at the informal trading chat price of 0.05, would put the average hourly cost at $555/hr.
> 
> NOTE 2: This proposal makes certain provision to reduce scope in case PKT price falls but in case of price rise, still asks for the entire payout.
> 
> 
> 
> EDIT: I mis-understood the application, it seems in fact to be 3.5mn PKT and is is unclear whether the number of hours is inclusive or exclusive of additional "extras".
> 
> 
> 
> NOTE 3: Since we need to make a decision about how to evaluate this, I propose that we evaluate it with all extras excluded.

**Comment by MeshMode** [comment]
I've updated the project proposal.

**Comment by cjdelisle** [comment]
We can only evaluate the project proposal as it was submitted by the deadline

**Comment by MeshMode** [comment]
> We can only evaluate the project proposal as it was submitted by the deadline

Does it mean that it's essential to upload new pull with edited proposal.

**Comment by cjdelisle** [comment]
Hello, 4 out of 5 of the votes were case and unfortunately your project was not accepted. As you might know, each vote is made on 5 different items:

* short term value
* long term value
* scope and use of resources (how much value/cost is the project)
* risk (of the project not going well)
* hazard (of real or perceived corruption)

Each evaluator casts a vote which is a number between zero and one. If an evaluator casts a zero vote on scope, risk or hazard, then they are indicating that they find the project unacceptable on that point, also if an evaluator casts a zero vote on both short term AND long term value, then they find the project unacceptable on those points. Below are the reviews which can be used for evolving proposals in the future by yourself and others.

## Ben

I will begin by acknowledging that this proposal is in an area I have little personal
experience, therefore it is difficult for me to evaluate risk and benefit for such an
initiative. I would have preferred if Milestone 1 itself is an entire proposal, as the
output will help those involved in PKT learn more about the ecosystem, along with a
execution plan. If this proposal is not funded, I encourage a follow-up proposal of such
narrower scope and lower budget be submitted. In its current form, I am still generally
supportive of the proposal, as it allows us to gather knowledge in this domain.
Regardless of whether the campaign is successful, I would prioritize documentation of
our learnings.

One area I believe the NS cannot commit to is taking on exchange risk with fiat. This
unfortunately has to be built in to the budget, since the process of the NS does not
have a way to handle that. I also think scoping down the proposal will help to manage
that risk. For this reason I have to reject the proposal as is.

I also highly recommend the formatting of the document be better structured and in .md.
This is incredibly hard to read.
* 'short': 0.7,
* 'long': 0.5,
* 'scope': 0.35,
* 'risk': 0.0,
* 'hazard': 0.4

## Adonis

I LOVE this idea. I want to see this proposal again
However there are some major issues that must be corrected first.
For these reasons I think the proposal must be disqualified on principle:

1. The proposal doesn't explain how it will acheive any of it's goals.
Even though I personally know Alex has done lobbying work in the past
and is at least in part responsible for the government (and therefore
global) adoption of IPv6, the proposal sounds like bullshit because
it doesn't detail well any of the work required to acheive the
milestones.
2. The project doesn't mention Alex's work with Anode (CJ and Adonis)
Which in vote_2020_02_29 is mentioned as an immediate disqualifier
at at the very least is bad form. Alex's relationship with Anode is
contractual and Anode builds technology based on PKT so I believe
there isn't much potential for conflict of interest, but still I believe
the relationship must be indicated publicly in the proposal
3. The propossal doesn't follow the template format.
Alex has submitted proposals before, I know he already knows the format.
There is no excuse for this sloppiness and I believe this alone
is grounds for disqualification.
The format is not difficult and maintaining as standard makes it easier
for the NS to get a sense of what's happening quickly and compare it to
other projects. It makes it easier for future authors to understand what
the submission process is and how to create a good project proposal.
It trains repeat submitters (of who Alex is an example)
to follow a stadard way of doing things.
4. The proposal asks for more PKT if the price drops. I'm very conflicted
about this. I sympathize that crypto fluxuates in value and that bills
must be paid but also this: are you kidding me? If PKT goes up, the
proposal don't ask for less of it. The people working on this project
are supposed to be incentivized by the increased value of PKT that they
hope will be the result of the increased value they've created for it
or by the goodwill they earn from contributing to an Internet technology
for the greater good of humanity. The NS is itself funded by PKT, not
a fiat, so when PKT goes down, we can't fund as many projects. Everyone
suffers. We shouldn't be taking additional resources away from potential
projects because one projects demands more in bad times than it got in
good. While practical, I think it's skeezy and I think it would set a
terrible precident to approve a proposal that had this condition.

If it weren't for these four things, I would probably grade this proposal
very highly. I love the idea and I believe Alex is the person to do it.
I think it falls within the scope of the NS and generally I think it's
proposed at a reasonable price.

### Short term
The proposal claims that there will be podcasts, larger followings,
politicans, influencers, and more talking about the project
Those are great things, but I don't think the immediate tangible benefits
are many in this case. I think those are the seeds that lead to a more
fruitful future.
I do believe that the talking points, assets, and presentation materials
will be useful in explaining the PKT projet to newcomers.

* 'short': 0.2,this is my actual vote
* 'short': 0.0,This is my 'disqualifier' vote

### Long term
PKT currently has a problem. People don't know how to talk about it.
One solution to this problem is to create talking points, presentation
materials, and assets that can be used to share the word.
On top of that, aligning influencers in the political spectrum that can
champion PKT as a tool rather than a weapon is important.
I'm aware that Alex has been able to gavlanize governments around the use
of IPv6, making it the dominant IP protocol to succeed IPv4.
If he can do the same for PKT, that would be fantastic.
Especially as crypto and other decentralized technologies are facing
scrutiny, regulation, and bad press. I worry that there is a such a
deep-seated fear of individuals saying or doing bad things that
governments (and corporations) will be willing to slowly reduce individual
rights and liberties around communication, finance, payments, and other
things that employ encryption technologies and are being decentralized.
PKT has tremendous potential for the creation of independently
owned businesses that benefit from fast micropayments and encrypted
communication.
If we don't advocate for that, who will?

* 'long': 0.8,this is my actual vote
* 'long': 0.0,This is my 'disqualifier' vote

### Scope
If I were to read "scope" here as "is this within the scope of the NS?"
Then I'd say "yes": 0.8.
Although I don't think of the Network Steward as a political organization
I believe this is a case where it must speak up and act. It's existence
is conditional governmental acceptance of crypto and encrypted data
transmission, both of which are sadly under fire.
In the same way that the Egg Farmers of America must lobby to advocate
for their rights, I believe so to must PKT.

* 'scope': .8,this is my actual vote
* 'scope': .0,This is my 'disqualifier' vote

### Risk
I see two potential issues here

The first is that wealthy politicians don't like PKT and that somehow they
are galvanized into negative action by the idea that private Internet
owned by peolpe other than ATT and Comcast. That would be terrible, but
would probably be inevitable with or without lobbying. In that
case it's better to lobby anyway because then at least we control the
narrative

The other is that this projects ends up turning into a marketing campaign
of youtube videos and podcasts hyping up PKT cash, which I think would
be terrible.

Since I've seen some of Lightman's work, I believe it won't be a series
of marketing videos, but since the proposal doesn't outline how things
will be done, how people will be qualified, or any examples of how
things will look or sound, I'm not inclined to trust it.

Other than that, I think the proposed timeline and budget is within reason
(except for the additional PKT hedge).

i would love to fund this alongside the User Operated Internet Fund
proposal. I think they complement each other well.

* 'risk': 0.2,this is my actual vote
* 'risk': .0,This is my 'disqualifier' vote

### Hazard
Cj and I do work with Alex Lightman through a company we have together.
so it could be percieved as a conflict of interest to favor this proposal
However, I believe the other criteria outweigh this possible bias.
I don't see that relationship stated in the proposal anywhere.
It's important to disclose possible conflicts of interest are
are referenced in vote_2020-02_29 as justification for disqualification.

* 'hazard': 0.1,this is my actual vote
* 'hazard': .0This is my 'disqualifier' vote

## Arceliar

### Short term
I don't expect any tangible short-term benefit. It may help to raise
awareness among politicians and regulatory bodies that there are some
political and regulatory road blocks in the way of innovation, but I don't
expect it to affect anything short-term. Whatever materials are produced
by the effort would likely be at least somewhat specific to some target
jurisdiction(s) (e.g. the US).
* 'short': .1,

### Long term
Any long-term benefits would have limited jurisdiction, so this doesn't
really have the same scale as some of the more technically innovative
proposals we've seen. The calculus on this would shift along with the
political landscape and changing regulations, so this could change if
reviewed again at a later date or as part of a carefully targeted
proposal. Right now, I expect technical problems and solutions, not
political ones, to make or break things for the PKT community.
* 'long': .1,

### Scope
Honestly, I have no idea how to score this one on principle. On the one
hand, I tend to think that directly funding political activity should be
considered out-of-scope for the NS. On the other hand, in some
hypothetical scenario where PKT was effectively banned, then there would
be hard to justify funding anything except lobbying. In any case, for this
proposal in particular, I don't think the milestone objectives are
sufficiently well defined.
* 'scope': 0.,

### Risk
The proposal states that each milestone requires the requested PKT or
enough to meet some budget requirement in national currency (at whatever
the exchange rate is at the time). I don't think that's something the NS
can or should agree to. I have to assume that, if the exchange rate
dropped and those funds were not made available, then the project wouldn't
be completed. That seems like a pointless and unnecessary risk to take,
given the volatility of crypto in general right now.
* 'risk': 0.,

### Hazard
There's some past association between applicants and NS members, which
would normally earn a penalty of some kind (perhaps 0.75 or so). However,
there's quite a few problems with the application itself, unrelated to the
risk and scope of the project:
1. The application is plain text, rather than following the markdown
template. This makes it more difficult to review (both by the NS and
any stake holders who want to monitor what the NS is approving). It
gives the impression of something that was thrown together at the
last minute, in a rush to submit something before the deadline.
2. The application lists a minimum budget in national currency, and
requests that additional funding be made available if the exchange
rate drops. As I noted in the risk criterion, that's not something I
think the NS can or should agree to. If we approve the proposal in
its current state, then it would imply that the NS agrees to make the
additional funds available, even if the exchange rate does not drop.
That would set a precedent that we accept applications with these
kinds of conditions, which I think would go against the interest of
the NS. Note that I think this would be disqualifying by itself, but
if it was the only issue with an otherwise promising application,
then I could possibly be convinced to allow that clause to be
removed.
3. I realize there was some followup on git after the submission window
closed, but we need to judge applications based on their state at the
close of submission, barring exceptional circumstances. Based on that
information, if we convert the budget to an hourly rate, then the
requested amount seems unreasonably high. This is extra problematic
when the applicants include known associates of the NS. Given the
minimum funding requirements (in national currency) mentioned before,
there's some implication that somebody worked out the minimum budget
needed for the proposal to succeed. I think some sort of breakdown of
that information would need to be included in the application,
otherwise we can't really justify the pay relative to hours worked.
Taken together, I don't think the NS should accept this application in its
current state, even if the project was otherwise in line with the
interests of the NS.
* 'hazard': 0.,

## Caleb

### Short term
This proposal is about building a non-partison lobbying campaign for Internet freedom, decentralization and
privacy. It has been said that if you don't tell your story then someone else will, and we have already begun
to see blockchain, crypto mining, privacy, and end-to-end encryption being cast in negative light. The US and EU
governments have been mulling bans on end-to-end encryption or mandatory backdoors, and cryptocurrencies are
increasingly are coming under regulatory scruteny with some discussion of outright bans on privacy coins such as
Monero. There is also an apparent PR war against crypto mining, with its supposed environmental impact getting
more media attention than that of even oil and coal exploration.

The communities around these technologies have clearly been bad at explaining their importance to society, and I
think there is very real possibility that governments around the world will begin to turn their backs on freedom
of communication, which would have very real short term impact on the ability of PKT to fulfill the vision.
* 'short': 3/5.0,

### Long term
It has been said that the price of liberty is eternal vigilance, and to this day we see autocracy,
totalitarianism, and oppression being proposed as "for the greater good", despite their historically poor
longevity and association to some of the most horrible atrocities in history.

Blockchains enable individuals to leverage simple freedom of communication and organize themselves in ways
that were previously not possible without dependence on government, existing businesses, and the banking
system. This puts blockchain at the forefront of the struggle for individual liberty, but blockchain
communities currently do not make significant concerted efforts to promote the freedoms upon which they
depend. So I think there is a long term necessity to continue to communicate about the importance of end-to-end
encryption, open source software, freedom of communication, privacy, and decentralization.
* 'long': 4/5.0,

### Scope
The project proposal does not follow the standard template which makes it difficult to understand, but it does
seem to have strong success criteria for the amount of declared work. The declared work seems to be 320+80+160+160
hours (or roughly 4.8 person-months) and the cost seems to be 3.5 million PKT. As the current price in the informal
trading chat seems to be roughly 5 cents, this makes the average hourly cost about 243 dollars per hour which is
a bit high. Furthermore there is a disclamer where it is mentioned that the milestones require 75k, 50k, and 50k
USD respectively which comes to the same numbers. Unfortunately the project is proposed in such a way that in case
of a rise in PKT price, the applicant wishes still to receive the entire payment but in case of a drop in PKT price,
they wish the payment to be more. I'm not ready to fail the project on this point but I think it has serious flaws.
* 'scope': 1/5.0,


### Risk
It is difficult to understand what is being requested, but the project proposal seems not to ask for any payment
until after the first deliverables are provided. The payment seems to be well spaced across the milestones, but
there seem to be many "extra options" and it is unclear if the applicant expects the Network Steward to vote on
each one of these as though it were a separate project, or which of these may or may not be included in the
declared time effort. My feeling is that if the proposal were re-phrased to be clear, then it would have fairly
good risk control, but as of now, the biggest risk is that the Network Steward might mis-interpret the proposal
and disagree with the applicant as to which milestones were delivered and what should be paid out, or how much
PKT should be paid, as the applicant is unsure if 3.5mn PKT is enough. I think I have to fail this project for
being under-specified, it is a good overall idea but the application is not developed enough to be handled
directly by the Network Steward.
* 'risk': 0/5.0,

### Hazard
As far as conflicts, the template was not used and the declaration is missing. There is a "minor" relationship
between Anode LLC (myself / Adonis) and one of the project participants (Alex Lightman), as he is also in a
software development contract with Anode. I don't think the applicant was intentionally hiding this fact, nor
that this constitutes a conflict for which we should step out from evaluation.
As far as "unfairly benefitting any one participant over any other", the hourly costs in the project are high
and it is unclear whether the declared hours are for the plain project or the project with "add-ons" included.
Most problematically, the costs are expressed in a "rachet" form where the applicant expects costs covered in
case of a decrease in PKT price but wants to keep the difference in case the price should go the other way.
* 'hazard': 2/5.0

**Pull request closed without merging**
