### PR TITLE
Update 2019_12_14_pkt-whitepaper-website.md

### PR DESCRIPTION
**Pull request by josh-berger**
Milestone #2 is complete: https://pkt.cash

### CODE REVIEW

**Review by cjdelisle — COMMENTED** [review]
Excellent website, I will approve conditioned on this https://github.com/pkt-cash/www-pkt-cash/pull/1 being accurate.

**Comment by benhylau** [comment]
New website looks great! Approval pending license confirm.

**Comment by josh-berger** [comment]
Those licenses are correct.

**Review by cjdelisle — APPROVED** [review]

**Review by neilalexander — APPROVED** [review]
Website is looking good!

**Review by benhylau — APPROVED** [review]

**Review by backupbrain — APPROVED** [review]
The website looks nice. In particular I like the clean colors, use of white space, approachable fonts, and use of scroll interactivity.

The Network Steward and Wallet sections look a little off somehow - they don't fit the rest of the site.

But generally everything looks fantastic.

**Review by Arceliar — APPROVED** [review]
I'm not 100% sure it includes all the information I'd ideally like to see, but I didn't notice anything obvious missing (and I assume adding content shouldn't be a big issue if e.g. some documentation needs to be expanded). I did not test if the contact page really works, but other than that everything seems to be in good shape. Very nice work.

**Comment by cjdelisle** [comment]
Accepted unanimously, will soon send around a transaction paying 5mn PKT to p9E3mhUtpinkvrn71AmoHNCoWYzMEmCiKq

**Pull request merged**
