### PR TITLE
Submission for milestone 1 completion

### PR DESCRIPTION
**Pull request by artrepreneur**
This is a request to merge milestone 1 completion for the pkt cash GUI wallet project.

### CODE REVIEW

**Comment by backupbrain** [comment]
I just opened the binary, it appears to work! In my book this is a resounding success of M1

**Comment by benhylau** [comment]
I haven't tested it, what platform binaries did cjd and @backupbrain test with? I agree the list seems sufficient to meet M1.

**Comment by cjdelisle** [comment]
> I haven't tested it, what platform binaries did cjd and @backupbrain test with? I agree the list seems sufficient to meet M1.

There's a DMG for apple in the repo "releases" section.

**Comment by cjdelisle** [comment]
Merging this because we have 4 people agreeing, @backupbrain didn't click the "approve" button but indicated as much in a comment.

**Pull request merged**
