### PR TITLE
Update on PktDesk and Request for 350,000 PKT

### PR DESCRIPTION
**Pull request by aamirmursleen**
I wanted to update you on the progress of PktDesk, and to request the release of 350,000 PKT as promised.

Over the past year, PktDesk has helped over 4500+ people to learn about PKT, according to Google Console. We have added 11 new articles and updated the old ones to ensure that the content is informative and up-to-date. As a result, the site is still enjoying 1st position for the majority of the keywords in Google.

If there is anything missing from the website or if there are any changes you would like to see, please do let me know. I would be happy to make any necessary changes to ensure that the website meets your expectations.

We are committed to continuing to improve PktDesk, and to reach an even wider audience. To help us do that, we kindly request that you release the promised 350,000 PKT. This payment will go a long way in helping us to cover our expenses and invest in further development.

Thank you for your continued support, and we look forward to hearing from you soon.

### CODE REVIEW

**Review by cjdelisle — APPROVED** [review]
pktdesk.com is still up, and provides helpful documentation for people wanting to participate in the PKT project. This proposal is structured a little bit uniquely, but based on the sums involved and the obvious good faith effort of the applicant, I think the correct course of action is to accept and pay out the entire project, and for us to add a "housekeeping" footnote to that effect.

Accept for me.

**Review by Arceliar — APPROVED** [review]
I agree with CJD's comment: a good faith effort has been made to meet the goals of the proposal (and AFAICT it was successful in meeting any quantifiable metrics), so I'm happy to approve this. A little "housekeeping"/cleanup of the project document would be appreciated, but I don't think that should block anything.

**Review by backupbrain — APPROVED** [review]
To me these improvements in the rankings are great. I hear great things about PktDesk from community members, and anything that honestly and accurately promote the spirit and technology of the PKT project is wonderful in my eyes.

**Review by neilalexander — APPROVED** [review]
The website seems to contain a lot of useful and interesting content and the rankings are seemingly evidence of its position right now, so happy to approve.

**Comment by cjdelisle** [comment]
Merging this request as it has been properly approved.

**Pull request merged**
