### PR TITLE
GUIDANCE REQUESTED: ns project proposal for PktPay

### PR DESCRIPTION
**Pull request by vk-vinay**
requesting ns support for this small project

### CODE REVIEW

**Comment by vk-vinay** [comment]
GUIDANCE REQUESTED

**Comment by cjdelisle** [comment]
Hello @vk-vinay , thanks for making this proposal!
I'm sorry it's taken this long for me to get back to you, and FYI the Network Steward is not able to, this is not the official opinion of the NS, this is just me making a suggestion.

While I can't guarantee anything, I think the general idea of an open source widget for accepting PKT in a website is a good thing. My advice to you would be to re-price your deliverables in a stable currency so as to protect yourself in case PKT decreases in value and to protect the community in case it rises while your project is ongoing.

Note that NS requires that the maximum amount of PKT for the project be specified, in case of a major decrease in the price of PKT, the project would be accepted partially delivered and the NS would consider a follow-on proposal to complete the work.

Please see this video: https://www.youtube.com/watch?v=b2sOigslBkM
And this template: https://cryptpad.fr/code/#/2/code/view/lHORne-EdOqRVL2kBQ7SCPpt8U9SoRF5utOCFjnaGVs/ which shows the process of delivering a milestone with the price of PKT at that time.

**Comment by vk-vinay** [comment]
@cjdelisle thank you for your guidance  will update proposal and commit initial work to https://github.com/vk-vinay/PktPay.git

**Comment by vk-vinay** [comment]
budget revised in stable currency

**Comment by cjdelisle** [comment]
Congratulations, this project was selected for funding.

It is still recommended to review the comments from the evaluators here: https://github.com/pkt-cash/ns-projects/blob/master/vote_2022_02_10.py

Wishing you an excellent project ahead.

Caleb

**Pull request merged**
