### PR TITLE
Update 2022_03_04_pkt_technical_documentation.md

### PR DESCRIPTION
**Pull request by jeremyberger33**
I am submitting the project milestone for technical documentation for PKT. When creating this proposal I expected it to take 133 hours to complete which it did. I also added a few extra steps for setting up a CLI wallet as I felt this was important to include so that miners could easily be able to have all the information when setting up a CLI Wallet. Please let me know if there is anything else I need to include. 

Thank you.

### CODE REVIEW

**Review by cjdelisle — APPROVED** [review]
This seems like a very easy project to validate. There were a list of 4 pieces of documentation and 4 pieces of documentation have been written.

For me this can be approved.

**Review by Arceliar — APPROVED** [review]
It's technical documentation. I haven't personally tested that it's accurate, but I don't have reason to doubt that it is.

My gut instinct is that 133 hours is a bit too long relative to the length of the documentation, but I have no way to know how much testing was required to reach and reproduce a working setup (but from experience, it always seems to be more than I'd expect), so I'm not going to argue with it.

In any case, the time it takes to produce the documentation isn't really the thing to think about, it's how much value it provides to the community, and I see no issues there. I think a good faith effort was made to produce the deliverables, that appears to have been successful, and I don't see any issues with the quality of the documentation itself, so this looks good to me.

**Review by backupbrain — COMMENTED** [review]
Documentation is readable, accurate and easy to follow

**Review by backupbrain — APPROVED** [review]

**Review by neilalexander — APPROVED** [review]
It looks like the documents cover what they need to and, on that basis, will approve.

**Comment by cjdelisle** [comment]
Merging this request as it has been properly approved.

**Pull request merged**
